### PR TITLE
add gzip and gunzip functions

### LINKED ISSUE #102: add gzip and gunzip functions
These functions would provide a convenient way to gzip-compress and decompress files within the library, similar to the existing zip and unzip functions.

### PR DESCRIPTION
**Pull request by laurio**
Please answer the following questions and leave the below in as part of your PR.

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/fs/blob/master/CHANGELOG.md) file with a description of the addressed issue.

resolves #102 (add gzip and gunzip functions)

### CODE REVIEW

**Comment by borkdude** [comment]
Some feedback / thoughts:

- Return value: maybe it would be nice to let gzip return the `.gzip` file as a return value?
- If you call `(fs/gzip ["README.md" "project.clj"])`, what is the expected file name? Do `.gzip` archives even support multiple files at all? Or does it create multiple `.gz` files? I think this is a potential source of confusion, maybe it's better to just accept one file for starters?
- Should we also support `(fs/gzip "README.md" "my.gz")`? so the second argument could be the destination _file_ instead of directory?
- The `zip` function first specifies the destination file (`foo.zip`) and then the entries, maybe we can align with that?

**Comment by laurio** [comment]
* Yes, imho, the `.gzip` file extension would be a more understandable default. I'll modify the `gzip` function to use the `.gzip` extension by default, instead of `.gz`, and have it return the gzip file as a return value.
* `gzip` is typically used to compress just a single file, as it doesn't retain any information about the original file boundaries. As a result, it's impossible to recover the original files individually from a single `.gzip` file. That's why I implemented the `gzip` function in such a way that it compresses each file into its own `.gzip` archive file. However, this doesn't feel very logical since people usually add multiple files into a tarball file first and then compress it with `gzip`. I'll modify it to only accept one input file for now.
* Yes, it would be better if the second parameter could be either an output directory or an archive file. However, how could we determine which one is specified?
* I'll modify the `gzip` function such that the gzip file parameter will be the first one, and the input file will follow it.

I've just learned that with the bash `gunzip` command, the original compressed file will be deleted after it has been successfully decompressed. The `-k` or `--keep` option preserves the archive file. Would it be a better approach to make the `gunzip` function behave similarly in Babashka and add a `keep` option to it when the user wants to preserve the archive?

**Comment by borkdude** [comment]
Let's not delete anything, I think being explicit in Clojure programs is better.

**Comment by borkdude** [comment]
My suggestions didn't imply (or I didn't intend to imply) to change `.gz` to `.gzip` btw, I just meant: return the file object as the return value.

**Comment by borkdude** [comment]
> Yes, it would be better if the second parameter could be either an output directory or an archive file. However, how could we determine which one is specified?

I think 

```
(gzip "README.md") => `README.md.gz` would be fine
```

```
(gzip "README.md" {:dir ...})
```

would work well for the output directory.

Perhaps another option to specify a full output path like

```
(gzip "README.md" {:out-file ...})
```

(name subject to improvement).

**Comment by laurio** [comment]
Pushed a new version of the gzip function, will add more tests tomorrow.

**Comment by borkdude** [comment]
Merged via other PR where I did a minor modification

**Pull request closed without merging**
