### PR TITLE
Add file-owner function (#97)

### PR DESCRIPTION
**Pull request by emilaasa**
Add the ability to retrieve the owner of a file or directory via Files/getOwner.

Please answer the following questions and leave the below in as part of your PR.

- [X] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [X] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [X] I have updated the [CHANGELOG.md](https://github.com/babashka/fs/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
Thanks! It seems the tests are failing.

**Comment by borkdude** [comment]
Adapted the PR and merged manually, thanks! I renamed the function to `owner`.

**Comment by emilaasa** [comment]
Nice! Thanks!

I tweaked the tests a bit: https://github.com/emilaasa/fs/blob/file-owner/test/babashka/fs_test.clj#L716

**Comment by borkdude** [comment]
ok, feel free to follow up with another PR for the test :)

**Pull request closed without merging**
