### PR TITLE
Add `force` flag to `delete-tree`

### LINKED ISSUE #119: `with-temp-dir` can raise a `AccessDeniedException` exception
This code fails with an exception:

```clojure
(fs/with-temp-dir [tmp-dir {:prefix "demo"}]
   (fs/create-dir (fs/path tmp-dir "my-dir")
                  {:posix-file-permissions "r-xr-xr-x"})
   (fs/create-file (fs/path tmp-dir "my-dir" "my-file")
                   {:posix-file-permissions "r--r--r--"}))
```
To delete a file, the parent directory must have the `OWNER_WRITE` permission.  

IMO, `with-temp-dir` shouldn't fail in this case.

A possible solution could be to add a flag to `delete-tree` (`:force?`?), to set the `OWNER_WRITE` permission in `:pre-visit-dir`, and then update `with-temp-dir` to invoke it with the flag set to true.

If it makes sense to you, I could open a PR.

### PR DESCRIPTION
**Pull request by jlesquembre**
Closes #119

Please answer the following questions and leave the below in as part of your PR.

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/fs/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
The posix stuff only works on linux/mac, perhaps there is another way which is more OS-agnostic.
Also, no need to set the file permission when the file already has the right permission, perhaps?

**Comment by jlesquembre** [comment]
The windows part, sure, I have to fix it, any tips on how to test it without a windows computer?

> Also, no need to set the file permission when the file already has the right permission, perhaps?

If the directory already have the right permissions (`OWNER_WRITE` and `OWNER_EXECUTE`) it doesn't change the permissions, or am I missing something?

**Comment by borkdude** [comment]
you're right

**Comment by borkdude** [comment]
Maybe File.setWriteable etc will suffice on Windows?

**Comment by jlesquembre** [comment]
> Maybe File.setWriteable etc will suffice on Windows?

Looks like that :-)  :

https://github.com/jlesquembre/fs/actions/runs/7268334832

**Comment by borkdude** [comment]
- [ ] Would there be any benefit of not changing the file permission on windows if the file is already writable? Is there a situation where this might throw an exception where the delete would have happened successfully, without first changing file permissions?
- [ ] Why not unify the code for windows and linux?

**Comment by jlesquembre** [comment]
> Would there be any benefit of not changing the file permission on windows if the file is already writable?

I don't think so, `File.setWriteable` seems idempotent

> Is there a situation where this might throw an exception where the delete would have happened successfully, without first changing file permissions?

The only case where we touch the permissions, and a delete would have happened successfully is on windows if a file is already writable. We call `.setWriteable` again, but it doesn't seem to make any difference.

> Why not unify the code for windows and linux?

I think mean here, right? https://github.com/jlesquembre/fs/blob/0468ac76bef9f054400de9da5030203c2351c15a/src/babashka/fs.cljc#L583-L584

The issue is that I don't want to touch the permissions if not necessary (with the exception for already writable files on windows, since it makes sense to me to just enforce that is writable and avoid calling `.canWrite`).

But the rules are different on posix vs windows:

- posix:
   - Read-only files can be deleted
   - Files can be deleted only if the parent directory has the "rwx" permissions
- windows:
   - Read-only files cannot be deleted
   - Parent directory permissions don't affect the delete operation of the child file.

I wrote some tests on my fork to test those assumptions, I can it to the PR if it makes sense:

https://github.com/jlesquembre/fs/commit/c4d4ccd4c4ee006f92ae03dbc0e56879e92a2130

https://github.com/jlesquembre/fs/actions/runs/7281870406

**Comment by borkdude** [comment]
OK, let's add those tests and I'll merge

**Comment by borkdude** [comment]
Btw, this issue might also be relevant to the above:

https://github.com/borkdude/deps.clj/issues/120#issuecomment-1865308756

**Comment by jlesquembre** [comment]
I added the tests, and a comment point out that the implementation is based on those assumptions.

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
